// Project:         Daggerfall Unity - iOS Touch Input Layer
// License:         MIT License
//
// MOBILE: diagnostic for the "location-sized pits with vertical walls, floors at the waterline"
// report (2026-09-10). Those pits are locations flattened to TerrainComputer.compute's 0.021
// floor (105 units) while the terrain around them is 300-700 units, and the flatten TARGET comes
// from the mod's own start-up world heightmap (mapPixelHeights / TerrainComputer.baseHeightmap).
// Device and iOS-Simulator runs agree byte for byte on every per-tile `sample` line, so the
// world heightmap is the thing to measure - and it is generated by ONE compute dispatch that
// needs no scene, no save and no arena2: MainHeightmapComputer over the whole 1000x500 map.
//
// This probe runs exactly that dispatch, with exactly InitializeWoodsFileHeightmap's uniforms
// and exactly its ten row bands, on the Mac's Metal, and censuses the result: NaNs, negatives,
// zeroes, values under the generator's own analytic floor ((BASEHEIGHT_MIN - 1) / newHeight =
// 99/5000 = 0.0198, the height GetBaseHeight assigns a pixel whose w.land is 0), and the byte
// histogram after Utility.ToBytes. It also prints the map pixels a Player.log named, so the
// numbers can be diffed against the device.
//
// The question it exists to answer: `[WoDTerrain] tile 112,161 ... base=0.0000` is ANALYTICALLY
// IMPOSSIBLE (baseHeight starts at 99/5000 and only `extraHeight` can pull it down), so either
// the fault-carving in heightSampling.cginc:288-297 really does drive whole map pixels to zero,
// or something on that path produces a NaN and Metal's saturate(NaN) == 0 turns it into one.
// ToBytes ((byte)(uint)(f * 255f)) has no NaN guard and no clamp, so both arrive as byte 0 -
// indistinguishable from ocean, and every location whose flatten sample touches such a pixel
// gets a 200-500 unit pit. Counting NaNs BEFORE ToBytes separates the two.
//
// CLI:
//   Unity -batchmode -quit -projectPath <proj> -executeMethod
//     DaggerfallWorkshop.Game.Mobile.EditorTools.MobileWoDWorldHeightmapProbe.Run -logFile <log>
//   env: DFU_WODPROBE_PIXELS="112,161 109,158"   extra map pixels to print (space separated)
//
// Editor-only diagnostics; touches nothing on disk and mutates no asset.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace DaggerfallWorkshop.Game.Mobile.EditorTools
{
    public static class MobileWoDWorldHeightmapProbe
    {
        const string mapDir = "Assets/Game/Mods/WorldOfDaggerfallTerrain/Assets/Maps/";
        const string iniPath = "Assets/Game/Mods/WorldOfDaggerfallTerrain/Assets/interesting_terrains.txt";
        const string computePath = "Assets/Resources/WoDTerrain/MainHeightmapComputer.compute";

        const int MapWidth = 1000;
        const int MapHeight = 500;

        // heightSampling.cginc: baseHeightMin = BASEHEIGHT_MIN - 1 = 99; baseHeight starts at
        // baseHeightMin / newHeight, so nothing below this can come out of the lerp itself.
        const float AnalyticFloor = 99f / 5000f;

        public static void Run()
        {
            var log = new StringBuilder();
            int exit = 0;
            try
            {
                exit = Probe(log);
            }
            catch (Exception ex)
            {
                log.AppendLine("[WoDProbe] FAILED: " + ex);
                exit = 2;
            }

            Debug.Log(log.ToString());
            if (Application.isBatchMode)
                EditorApplication.Exit(exit);
        }

        static int Probe(StringBuilder log)
        {
            log.AppendLine("[WoDProbe] graphics=" + SystemInfo.graphicsDeviceType
                + " computeSupport=" + SystemInfo.supportsComputeShaders);

            var cs0 = AssetDatabase.LoadAssetAtPath<ComputeShader>(computePath);
            if (cs0 == null) { log.AppendLine("[WoDProbe] FAILED: no compute shader at " + computePath); return 2; }

            // MOBILE: the runtime does NOT use the project's copies of the control maps - it uses the
            // ones inside wod-terrain.dfmod (InterestingTerrains.TryLoadBundleAssets ->
            // Mod.GetAsset<Texture2D>). ApplyAll builds that bundle through the mod-pack texture
            // rules, so the bundle's deriv/biome map can differ in size, format or filtering from the
            // project asset - and the generator's output is a function of exactly those two textures.
            // DFU_WODPROBE_BUNDLE points the probe at the bundle so the two can be compared.
            Texture2D biome, deriv;
            TextAsset ini;
            string bundlePath = Environment.GetEnvironmentVariable("DFU_WODPROBE_BUNDLE");
            AssetBundle bundle = null;
            if (!string.IsNullOrEmpty(bundlePath))
            {
                bundle = AssetBundle.LoadFromFile(bundlePath);
                if (bundle == null) { log.AppendLine("[WoDProbe] FAILED: could not load bundle " + bundlePath); return 2; }
                log.AppendLine("[WoDProbe] source: BUNDLE " + bundlePath);
                biome = FindInBundle<Texture2D>(bundle, "daggerfall_heightmap");
                deriv = FindInBundle<Texture2D>(bundle, "daggerfall_deriv_map");
                ini = FindInBundle<TextAsset>(bundle, "interesting_terrains");
            }
            else
            {
                log.AppendLine("[WoDProbe] source: PROJECT assets");
                biome = AssetDatabase.LoadAssetAtPath<Texture2D>(mapDir + "daggerfall_heightmap.png");
                deriv = AssetDatabase.LoadAssetAtPath<Texture2D>(mapDir + "daggerfall_deriv_map.png");
                ini = AssetDatabase.LoadAssetAtPath<TextAsset>(iniPath);
            }
            if (biome == null || deriv == null || ini == null)
            {
                log.AppendLine("[WoDProbe] FAILED: biome=" + (biome != null) + " deriv=" + (deriv != null) + " ini=" + (ini != null));
                return 2;
            }

            // The control maps are authored at 5000x2500 (5 texels per map pixel). What the shader
            // actually samples is whatever the importer produced, so report both.
            log.AppendLine(string.Format("[WoDProbe] deriv imported {0}x{1} format={2} mips={3} sRGB-ish={4}",
                deriv.width, deriv.height, deriv.format, deriv.mipmapCount, GraphicsFormatIsSrgb(deriv)));
            log.AppendLine(string.Format("[WoDProbe] biome imported {0}x{1} format={2} mips={3}",
                biome.width, biome.height, biome.format, biome.mipmapCount));

            Monobelisk.TerrainComputerParams csParams = ScriptableObject.CreateInstance<Monobelisk.TerrainComputerParams>();
            csParams.FromIniData(new IniParser.Parser.IniDataParser().Parse(ini.text));

            var cs = UnityEngine.Object.Instantiate(cs0);
            int k = cs.FindKernel("CSMain");

            // Exactly TerrainComputer.InitializeWoodsFileHeightmap's uniforms.
            cs.SetFloat("newHeight", Monobelisk.Constants.TERRAIN_HEIGHT);
            cs.SetFloat("maxTerrainHeight", 2308.5f);
            cs.SetFloat("scaledOceanElevation", 27.2f);
            cs.SetFloat("baseHeightScale", 8f);
            cs.SetFloat("noiseMapScale", 4f);
            cs.SetFloat("extraNoiseScale", 10f);
            cs.SetVector("terrainSize", new Vector2(Monobelisk.TerrainComputer.StartupSampleDim, MapHeight));
            cs.SetVector("terrainPosition", Vector2.zero);
            cs.SetTexture(k, "BiomeMap", biome);
            cs.SetTexture(k, "DerivMap", deriv);
            csParams.ApplyToCS(cs);

            var dummySizes = Monobelisk.TerrainComputer.StartupDummySizes;
            var result = new ComputeBuffer(MapWidth * MapHeight, sizeof(float));
            var shm = new ComputeBuffer(dummySizes.shm, sizeof(float));
            var lhm = new ComputeBuffer(dummySizes.lhm, sizeof(float));
            var floats = new float[MapWidth * MapHeight];

            try
            {
                shm.SetData(new float[dummySizes.shm]);
                lhm.SetData(new float[dummySizes.lhm]);
                cs.SetBuffer(k, "Result", result);
                cs.SetBuffer(k, "shm", shm);
                cs.SetBuffer(k, "lhm", lhm);
                cs.SetInt("sd", Monobelisk.TerrainComputer.StartupShmDim);
                cs.SetInt("ld", Monobelisk.TerrainComputer.StartupLhmDim);
                cs.SetInt("hDim", Monobelisk.TerrainComputer.StartupSampleDim);
                cs.SetFloat("div", Monobelisk.TerrainComputer.StartupSampleDiv);

                // A sentinel the kernel never writes, so "was this element dispatched at all?" is
                // answerable: a banded readback that loses a row would leave the sentinel behind.
                const float Sentinel = -12345f;
                for (int i = 0; i < floats.Length; i++) floats[i] = Sentinel;
                result.SetData(floats);

                var bands = Monobelisk.TerrainComputer.Bands(MapHeight, Monobelisk.TerrainComputer.StartupBands);
                foreach (var band in bands)
                {
                    cs.SetInt("yOffset", band.yStart);
                    cs.Dispatch(k, MapWidth / 10, band.rows / Monobelisk.TerrainComputer.GroupRowsY, 1);
                    int offset = Monobelisk.TerrainComputer.ReadbackStartRow(MapHeight, band.yStart, band.rows) * MapWidth;
                    result.GetData(floats, offset, offset, band.rows * MapWidth);
                }
                log.AppendLine("[WoDProbe] dispatched " + bands.Length + " bands");

                // ---- census -------------------------------------------------------------
                int nans = 0, infs = 0, negatives = 0, zeros = 0, underFloor = 0, unwritten = 0, atOne = 0;
                float min = float.MaxValue, max = float.MinValue;
                var firstNan = new List<string>();
                var firstZero = new List<string>();
                var firstUnder = new List<string>();
                for (int i = 0; i < floats.Length; i++)
                {
                    float f = floats[i];
                    int px = i % MapWidth, py = i / MapWidth;   // WOODS layout: index = x + y * MapWidth
                    if (float.IsNaN(f)) { nans++; if (firstNan.Count < 12) firstNan.Add(px + "," + py); continue; }
                    if (float.IsInfinity(f)) { infs++; continue; }
                    if (f == Sentinel) { unwritten++; continue; }
                    if (f < min) min = f;
                    if (f > max) max = f;
                    if (f < 0f) negatives++;
                    if (f == 0f) { zeros++; if (firstZero.Count < 12) firstZero.Add(px + "," + py); }
                    else if (f < AnalyticFloor - 1e-6f) { underFloor++; if (firstUnder.Count < 12) firstUnder.Add(string.Format("{0},{1}={2:F5}", px, py, f)); }
                    if (f >= 1f) atOne++;
                }

                log.AppendLine(string.Format(
                    "[WoDProbe] census of {0} floats: nan={1} inf={2} unwritten={3} negative={4} exactly0={5} underFloor({6:F4})={7} saturated1={8} min={9:F6} max={10:F6}",
                    floats.Length, nans, infs, unwritten, negatives, zeros, AnalyticFloor, underFloor, atOne, min, max));
                if (firstNan.Count > 0) log.AppendLine("[WoDProbe] first NaN pixels: " + string.Join(" ", firstNan.ToArray()));
                if (firstZero.Count > 0) log.AppendLine("[WoDProbe] first exact-zero pixels: " + string.Join(" ", firstZero.ToArray()));
                if (firstUnder.Count > 0) log.AppendLine("[WoDProbe] first under-floor pixels: " + string.Join(" ", firstUnder.ToArray()));

                // ---- the bytes the shader and the travel map actually see ----------------
                // MOBILE: (F2) the counting overload - `nonFinite` is how many floats ToBytes had to
                // substitute a neighbour byte for (NaN / inf / negative). On the Mac this has always
                // been 0; the device's `holes 14519` is what it exists to attribute.
                int toBytesNonFinite;
                var bytes = Monobelisk.Utility.ToBytes(floats, out toBytesNonFinite);
                log.AppendLine("[WoDProbe] ToBytes substituted (nan/inf/negative) = " + toBytesNonFinite);
                int byte0 = 0, byteUnder5 = 0;
                var hist = new int[256];
                for (int i = 0; i < bytes.Length; i++)
                {
                    hist[bytes[i]]++;
                    if (bytes[i] == 0) byte0++;
                    if (bytes[i] < 5) byteUnder5++;
                }
                log.AppendLine(string.Format(
                    "[WoDProbe] after ToBytes: byte==0 {0} ({1:F3}% of the map), byte<5 {2}; ocean floor byte is 5 (99/5000*255=5.05)",
                    byte0, 100.0 * byte0 / bytes.Length, byteUnder5));
                var top = new StringBuilder();
                for (int b = 0; b <= 24; b++) top.Append(b).Append(':').Append(hist[b]).Append(' ');
                log.AppendLine("[WoDProbe] byte histogram 0..24: " + top);

                // A byte 0 that is NOT a NaN and NOT a real ocean pixel is the pit source: report
                // how many byte-0 pixels have a land neighbour above the beach, i.e. sit in land.
                int isolated = 0;
                var isolatedList = new List<string>();
                for (int y = 1; y < MapHeight - 1; y++)
                {
                    for (int x = 1; x < MapWidth - 1; x++)
                    {
                        if (bytes[x + y * MapWidth] != 0) continue;
                        int landNeighbours = 0;
                        for (int dy = -1; dy <= 1; dy++)
                            for (int dx = -1; dx <= 1; dx++)
                            {
                                if (dx == 0 && dy == 0) continue;
                                if (bytes[(x + dx) + (y + dy) * MapWidth] >= 10) landNeighbours++;
                            }
                        if (landNeighbours >= 5)
                        {
                            isolated++;
                            if (isolatedList.Count < 24) isolatedList.Add(x + "," + y);
                        }
                    }
                }
                log.AppendLine(string.Format(
                    "[WoDProbe] byte-0 pixels with >=5 of 8 neighbours at byte>=10 (a hole inside land, not a coast): {0}", isolated));
                log.AppendLine("[WoDProbe] TerrainComputer.CountWorldHeightmapHoles (byte<=5 ringed by land) = "
                    + Monobelisk.TerrainComputer.CountWorldHeightmapHoles(bytes));

                // MOBILE: (D4) production repairs those holes between ToBytes and the two readers, so
                // the probe runs the same call and re-censuses: `repaired` should equal the count above
                // and `remaining` should be ~0 (only holes the two passes could not reach). The byte
                // deltas are reported so the change to the map is visible as a number, not a claim.
                var beforeRepair = (byte[])bytes.Clone();
                int repairedHoles = Monobelisk.TerrainComputer.RepairWorldHeightmapHoles(
                    bytes, MapWidth, MapHeight);
                int changedBytes = 0, maxByteDelta = 0;
                for (int i = 0; i < bytes.Length; i++)
                {
                    int d = bytes[i] - beforeRepair[i];
                    if (d == 0) continue;
                    changedBytes++;
                    if (d > maxByteDelta) maxByteDelta = d;
                }
                log.AppendLine(string.Format(
                    "[WoDProbe] RepairWorldHeightmapHoles: repaired {0}, remaining {1}, bytes changed {2}, max byte delta +{3}",
                    repairedHoles, Monobelisk.TerrainComputer.CountWorldHeightmapHoles(bytes),
                    changedBytes, maxByteDelta));

                // The pit fix lives in TerrainComputer.compute; make sure it still compiles here
                // rather than discovering it in an xcodebuild log.
                var tileCs = AssetDatabase.LoadAssetAtPath<ComputeShader>("Assets/Resources/WoDTerrain/TerrainComputer.compute");
                if (tileCs == null) log.AppendLine("[WoDProbe] TerrainComputer.compute MISSING");
                else
                {
                    int msgs = UnityEditor.ShaderUtil.GetComputeShaderMessageCount(tileCs);
                    log.AppendLine("[WoDProbe] TerrainComputer.compute messages=" + msgs
                        + " kernelTerrainComputer=" + tileCs.FindKernel("TerrainComputer")
                        + " kernelTilemapComputer=" + tileCs.FindKernel("TilemapComputer"));
                    if (msgs > 0)
                        foreach (var m in UnityEditor.ShaderUtil.GetComputeShaderMessages(tileCs))
                            log.AppendLine("[WoDProbe]   " + m.severity + ": " + m.message + " | " + m.messageDetails);
                }
                if (isolatedList.Count > 0) log.AppendLine("[WoDProbe] holes: " + string.Join(" ", isolatedList.ToArray()));

                // ---- named pixels, for diffing against a Player.log ---------------------
                foreach (var p in NamedPixels())
                {
                    int i = p.x + p.y * MapWidth;
                    if (i < 0 || i >= floats.Length) continue;
                    log.AppendLine(string.Format("[WoDProbe] pixel {0},{1}: float={2:F6} byte={3} base={4:F4}",
                        p.x, p.y, floats[i], bytes[i], bytes[i] / 255f));
                }
            }
            finally
            {
                if (result != null) result.Release();
                if (shm != null) shm.Release();
                if (lhm != null) lhm.Release();
                UnityEngine.Object.DestroyImmediate(cs);
                UnityEngine.Object.DestroyImmediate(csParams);
            }

            return 0;
        }

        static T FindInBundle<T>(AssetBundle ab, string name) where T : UnityEngine.Object
        {
            foreach (var o in ab.LoadAllAssets<T>())
                if (string.Equals(o.name, name, StringComparison.OrdinalIgnoreCase))
                    return o;
            return null;
        }

        static bool GraphicsFormatIsSrgb(Texture2D t)
        {
            return t.graphicsFormat.ToString().IndexOf("SRGB", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        struct Px { public int x, y; }

        static List<Px> NamedPixels()
        {
            var list = new List<Px>();
            // The pixels the 2026-09-10 device and simulator logs both reported, plus the anomaly.
            int[,] def = {
                { 112, 161 }, { 111, 161 }, { 112, 160 }, { 112, 162 }, { 113, 161 },
                { 109, 158 }, { 106, 155 }, { 106, 156 }, { 106, 157 }, { 106, 158 },
                { 460, 51 },
            };
            for (int i = 0; i < def.GetLength(0); i++) list.Add(new Px { x = def[i, 0], y = def[i, 1] });

            string extra = Environment.GetEnvironmentVariable("DFU_WODPROBE_PIXELS");
            if (!string.IsNullOrEmpty(extra))
            {
                // "x,y" pairs arrive already split on the comma, so consume two at a time.
                var nums = extra.Split(new[] { ' ', ',', ';' }, StringSplitOptions.RemoveEmptyEntries);
                for (int i = 0; i + 1 < nums.Length; i += 2)
                {
                    int x, y;
                    if (int.TryParse(nums[i], NumberStyles.Integer, CultureInfo.InvariantCulture, out x)
                        && int.TryParse(nums[i + 1], NumberStyles.Integer, CultureInfo.InvariantCulture, out y))
                        list.Add(new Px { x = x, y = y });
                }
            }
            return list;
        }
    }
}
